version: '3.5'

networks:
  work-docker-net:
    driver: bridge
    ipam: 
      config: 
        - subnet: ${PROJECT_IP}/16
services: #表示这是一组服务 
### PHP-FPM #########################################
  php-fpm:
    build:
      context: docker-build/php-fpm
    container_name: php-fpm #应用的mysql的镜像名称
    expose:
      - "9000"
    restart: always #docker服务重启后nginx的docker容器也重启
    volumes:
      - ./docker-build/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
      - ${WORKSPACE}:/var/www:cached
    networks:
      work-docker-net:
        ipv4_address: ${PROJECT_IP_24}.1
    links:
      - mysql
      - mongo
      - redis
    # networks:
    #   - backend
### NGINX Server #########################################
  nginx:
    build:
      context: docker-build/nginx
      args:
        - CHANGE_SOURCE=${CHANGE_SOURCE}
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
        - http_proxy
        - https_proxy
        - no_proxy
    container_name: nginx
    volumes:
      - ${WORKSPACE}:/var/www:cached
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HOST_HTTP_PORT}:80"
      - "${NGINX_HOST_HTTPS_PORT}:443"
    restart: always #docker服务重启后nginx的docker容器也重启
    links:
      - php-fpm # 连接php的docker容器 会在host文件生成 php 192.169.1.101(php 容器的局域网ip)
    # depends_on:
    #   - php-fpm
    networks:
      work-docker-net:
        ipv4_address: ${PROJECT_IP_24}.2
  redis:
    build:
      context: docker-build/redis
    # image: redis
    container_name: redis
    restart: always #docker服务重启后nginx的docker容器也重启
    ports:
      - "6379:6379" #映射的端口，redis容器的6379端口映射到本地的6379端口，可以通过ip:6379访问容器
    networks:
      work-docker-net:
        ipv4_address: ${PROJECT_IP_24}.3
    volumes:
      # 挂载数据目录
      - ${DOCKER_DATA_PATH}${REDIS_DATA_PATH}:/data
  mysql:
    build:
      context: docker-build/mysql
    # image: mysql #应用的mysql的镜像名称
    container_name: mysql #应用的mysql的镜像名称
    restart: always #docker服务重启后nginx的docker容器也重启
    ports:
      - "3306:3306" #映射的端口，redis容器的6379端口映射到本地的6379端口，可以通过ip:6379访问容器
    environment:
      MYSQL_ROOT_PASSWORD: root_password # root用户的密码
      MYSQL_USER: user # 创建新用户
      MYSQL_PASSWORD: user_password # 新用户的密码
    volumes:
      # - ${DOCKER_DATA_PATH}mysql-conf:/etc/mysql #本地mysql映射到docker
      - ${DOCKER_DATA_PATH}${MYSQL_DATA_PATH}:/var/lib/mysql #本地mysql映射到docker
    networks:
      work-docker-net:
        ipv4_address: ${PROJECT_IP_24}.4
  mongo:
    build:
      context: docker-build/mongodb
    # image: mongo
    container_name: mongo
    restart: always #docker服务重启后nginx的docker容器也重启
    ports:
      - "27017:27017" #映射的端口，redis容器的6379端口映射到本地的6379端口，可以通过ip:6379访问容器
    volumes:
      # 挂载数据目录
      - ${DOCKER_DATA_PATH}${MONGODB_DATA_PATH}:/data/db
    networks:
      work-docker-net:
        ipv4_address: ${PROJECT_IP_24}.5
